/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculadora.h"

bool_t
xdr_float_type (XDR *xdrs, float_type *objp)
{
	register int32_t *buf;

	 if (!xdr_float (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_char_type (XDR *xdrs, char_type *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_vector_type (XDR *xdrs, vector_type *objp)
{
	register int32_t *buf;

	 if (!xdr__vector (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_matriz_type (XDR *xdrs, matriz_type *objp)
{
	register int32_t *buf;

	 if (!xdr_matriz (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_calculo1 (XDR *xdrs, calculo1 *objp)
{
	register int32_t *buf;

	 if (!xdr_namecalculo (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_calculo2 (XDR *xdrs, calculo2 *objp)
{
	register int32_t *buf;

	 if (!xdr_namecalculo2 (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_calculo3 (XDR *xdrs, calculo3 *objp)
{
	register int32_t *buf;

	 if (!xdr_namecalculo3 (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_resultado1 (XDR *xdrs, resultado1 *objp)
{
	register int32_t *buf;

	 if (!xdr_float (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_resultado2 (XDR *xdrs, resultado2 *objp)
{
	register int32_t *buf;

	 if (!xdr__vector (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_resultado3 (XDR *xdrs, resultado3 *objp)
{
	register int32_t *buf;

	 if (!xdr_matriz (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_namecalculo (XDR *xdrs, namecalculo *objp)
{
	register int32_t *buf;

	 if (!xdr_float_type (xdrs, &objp->uno))
		 return FALSE;
	 if (!xdr_char_type (xdrs, &objp->operacion))
		 return FALSE;
	 if (!xdr_float_type (xdrs, &objp->dos))
		 return FALSE;
	return TRUE;
}

bool_t
xdr__vector (XDR *xdrs, _vector *objp)
{
	register int32_t *buf;

	 if (!xdr_float_type (xdrs, &objp->f1))
		 return FALSE;
	 if (!xdr_float_type (xdrs, &objp->f2))
		 return FALSE;
	 if (!xdr_float_type (xdrs, &objp->f3))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_namecalculo2 (XDR *xdrs, namecalculo2 *objp)
{
	register int32_t *buf;

	 if (!xdr_vector_type (xdrs, &objp->uno))
		 return FALSE;
	 if (!xdr_char_type (xdrs, &objp->operacion))
		 return FALSE;
	 if (!xdr_vector_type (xdrs, &objp->dos))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_matriz (XDR *xdrs, matriz *objp)
{
	register int32_t *buf;

	 if (!xdr_vector_type (xdrs, &objp->v1))
		 return FALSE;
	 if (!xdr_vector_type (xdrs, &objp->v2))
		 return FALSE;
	 if (!xdr_vector_type (xdrs, &objp->v3))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_namecalculo3 (XDR *xdrs, namecalculo3 *objp)
{
	register int32_t *buf;

	 if (!xdr_matriz_type (xdrs, &objp->uno))
		 return FALSE;
	 if (!xdr_char_type (xdrs, &objp->operacion))
		 return FALSE;
	 if (!xdr_matriz_type (xdrs, &objp->dos))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_calculadora_res1 (XDR *xdrs, calculadora_res1 *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->errno))
		 return FALSE;
	switch (objp->errno) {
	case 0:
		 if (!xdr_resultado1 (xdrs, &objp->calculadora_res1_u.solucion))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_calculadora_res2 (XDR *xdrs, calculadora_res2 *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->errno))
		 return FALSE;
	switch (objp->errno) {
	case 0:
		 if (!xdr_resultado2 (xdrs, &objp->calculadora_res2_u.solucion))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_calculadora_res3 (XDR *xdrs, calculadora_res3 *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->errno))
		 return FALSE;
	switch (objp->errno) {
	case 0:
		 if (!xdr_resultado3 (xdrs, &objp->calculadora_res3_u.solucion))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}
