/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"


void
calculadoraprog_1(char *host, float_type uno, char_type *op, float_type dos)
{
	CLIENT *clnt;
	calculadora_res1  *result_1;
	calculo1 calculadora_1_arg1;
	calculadora_1_arg1.uno = uno;
	calculadora_1_arg1.dos = dos;
	calculadora_1_arg1.operacion = op;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCULADORAPROG, CALCULADORA1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = calculadora_1(calculadora_1_arg1, clnt);
	if (result_1 == (calculadora_res1 *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
		printf("Resultado: %0.6f\n",result_1->calculadora_res1_u.solucion);
	}
	xdr_free(xdr_calculadora_res1, &result_1);

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
calculadoraprog_2(char *host, vector_type uno, char_type operacion, vector_type dos)
{
	CLIENT *clnt;
	calculadora_res2  *result_1;
	calculo2 calculadora_2_arg1;
	calculadora_2_arg1.uno = uno;
	calculadora_2_arg1.operacion = operacion;
	calculadora_2_arg1.dos = dos;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCULADORAPROG, CALCULADORA2, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = calculadora_2(calculadora_2_arg1, clnt);
	if (result_1 == (calculadora_res2 *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
		printf("Vector resultante: %0.3f %0.3f %0.3f\n",result_1->calculadora_res2_u.solucion.f1,
			result_1->calculadora_res2_u.solucion.f2, result_1->calculadora_res2_u.solucion.f3);
	}
	xdr_free(xdr_calculadora_res2, &result_1);

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
calculadoraprog_3(char *host, matriz_type uno, char_type operacion, matriz_type dos)
{
	CLIENT *clnt;
	calculadora_res3  *result_1;
	calculo3 calculadora_3_arg1;
	calculadora_3_arg1.uno = uno;
	calculadora_3_arg1.operacion = operacion;
	calculadora_3_arg1.dos = dos;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCULADORAPROG, CALCULADORA3, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = calculadora_3(calculadora_3_arg1, clnt);
	if (result_1 == (calculadora_res3 *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
		printf("Matriz resultante:\n %0.2f %0.2f %0.2f\n %0.2f %0.2f %0.2f\n %0.2f %0.2f %0.2f\n",
		result_1->calculadora_res3_u.solucion.v1.f1, result_1->calculadora_res3_u.solucion.v1.f2,
		result_1->calculadora_res3_u.solucion.v1.f3,result_1->calculadora_res3_u.solucion.v2.f1, 
		result_1->calculadora_res3_u.solucion.v2.f2,result_1->calculadora_res3_u.solucion.v2.f3,
		result_1->calculadora_res3_u.solucion.v3.f1, result_1->calculadora_res3_u.solucion.v3.f2,
		result_1->calculadora_res3_u.solucion.v3.f3);
	}
	xdr_free(xdr_calculadora_res3, &result_1);

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	//Comprobamos que el número de argumentos es válido
	if ((argc != 5) && (argc != 9 ) && (argc !=  21)) {
		printf ("Para usar la calculadora simple: %s server_host float operación float\n", argv[0]);
		printf("Las operaciones simples implementadas son las siguientes:\n");
		printf("Pulse +  para sumar\n");
		printf("Pulse -  para restar\n");
		printf("Pulse x  para multiplicar\n");
		printf("Pulse /  para dividir\n");
		printf("Pulse m para realizar el módulo\n");
		printf("Pulse p para calcular porcentajes, calcula porcentajes (ej: 20 p 34, calcula el 20 porciento de 24)\n");
		printf("Pulse r para calcular la raiz de un número, ej: 4 r presición, calcula la raiz de 4 con una cierta presición\n");
		printf("Pulse ^ para realizar el elevado\n\n");

		printf("Para usar la calculadora de vectores de 3 coordenadas:%s server_host vector1.x vector1.y vector1.z operación vector2.x vector2.y vector2.z\n", argv[0]);
		printf("Las operaciones con vectores de 3 coordenadas implementadas son las siguientes:\n");
		printf("Pulse + para sumar los vectores\n");
		printf("Pulse - para restar los vectores\n");
		printf("Pulse x para hacer el producto escalar de los vectores\n");
		printf("Pulse v para hacer el producto vectorial de los vectores\n\n");

		printf("Para usar la calculadora de matrices 3x3:%s server_host operacion matriz1[0][0] matriz1[0][1] matriz1[0][2] matriz1[1][0] matriz1[1][1] matriz1[1][2] matriz1[2][0] matriz1[2][1] matriz1[2][2] matriz2[0][0] matriz2[0][1] matriz2[0][2] matriz2[1][0] matriz2[1][1] matriz2[1][2] matriz2[2][0] matriz2[2][1] matriz2[2][2] \n", argv[0]);
		printf("Las operaciones con matrices 3x3 implementadas son las siguientes:\n");
		printf("Pulse + para sumar las matrices\n");
		printf("Pulse - para restar las matrices\n");
		printf("Pulse x para hacer el producto de matrices\n");
		printf("Pulse e para hacer el producto escalar de matrices\n\n");


		exit (1);
	}

	host = argv[1];

	if(argc == 5){ //Operaciones simples

		//Comprobamos que el usuario no intente dividir por 0
		if((strcmp(argv[3], "/") == 0) && (atof(argv[4]) == 0)){
			printf("No se puede dividir entre 0\n");
			exit(1);

		}

		//Comprobamos que el usuario introduzca una operación válida
		if((strcmp(argv[3], "+") != 0) && (strcmp(argv[3], "-") != 0) && (strcmp(argv[3], "x") != 0)
			&& (strcmp(argv[3], "/") != 0) && (strcmp(argv[3], "m") != 0) && (strcmp(argv[3], "^") != 0)
			&& (strcmp(argv[3], "p") != 0) && (strcmp(argv[3], "r") != 0)){
			printf("La operación introducida es incorrecta, por favor seleccione una válida.\n\n");
			printf ("Para usar la calculadora simple: %s server_host float operación float\n", argv[0]);
			printf("Las operaciones simples implementadas son las siguientes:\n");
			printf("Pulse +  para sumar\n");
			printf("Pulse -  para restar\n");
			printf("Pulse x  para multiplicar\n");
			printf("Pulse /  para dividir\n");
			printf("Pulse m para realizar el módulo\n");
			printf("Pulse p para calcular porcentajes, calcula porcentajes (ej: 20 p 34, calcula el 20 porciento de 24)\n");
			printf("Pulse r para calcular la raiz de un número, ej: 4 r presición, calcula la raiz de 4 con una cierta presición\n");
			printf("Pulse ^ para realizar el elevado\n\n");
			exit(1);
		}

		calculadoraprog_1 (host, atof(argv[2]), argv[3], atof(argv[4]));

	}else if(argc == 9){//Operaciones con vectores

		//Comprobamos que el usuario introduzca una operación válida
		if((strcmp(argv[5], "+") != 0) && (strcmp(argv[5], "-") != 0) && (strcmp(argv[5], "x") != 0)
			&& (strcmp(argv[5], "v") != 0) ){
			printf("La operación introducida es incorrecta, por favor seleccione una válida.\n\n");
			printf("Para usar la calculadora de vectores de 3 coordenadas:%s server_host vector1.x vector1.y vector1.z operación vector2.x vector2.y vector2.z\n", argv[0]);
			printf("Las operaciones con vectores de 3 coordenadas implementadas son las siguientes:\n");
			printf("Pulse + para sumar los vectores\n");
			printf("Pulse - para restar los vectores\n");
			printf("Pulse x para hacer el producto escalar de los vectores\n");
			printf("Pulse v para hacer el producto vectorial de los vectores\n\n");
			printf("Pulse v para hacer el producto escalar de matrices\n\n");
			exit(1);

		}

		vector_type v1;
		vector_type v2;

		v1.f1 = atof(argv[2]);
		v1.f2 = atof(argv[3]);
		v1.f3 = atof(argv[4]);

		v2.f1 = atof(argv[6]);
		v2.f2 = atof(argv[7]);
		v2.f3 = atof(argv[8]);

		calculadoraprog_2 (host, v1, argv[5], v2);

	}else if(argc == 21){//Operaciones con matrices

		//Comprobamos que el usuario introduzca una operación válida
		if((strcmp(argv[2], "+") != 0) && (strcmp(argv[2], "-") != 0) && (strcmp(argv[2], "x") != 0)
			&& (strcmp(argv[2], "e") != 0) ){
			printf("La operación introducida es incorrecta, por favor seleccione una válida.\n\n");
			printf("Para usar la calculadora de matrices 3x3:%s server_host operacion matriz1[0][0] matriz1[0][1] matriz1[0][2] matriz1[1][0] matriz1[1][1] matriz1[1][2] matriz1[2][0] matriz1[2][1] matriz1[2][2] matriz2[0][0] matriz2[0][1] matriz2[0][2] matriz2[1][0] matriz2[1][1] matriz2[1][2] matriz2[2][0] matriz2[2][1] matriz2[2][2] \n", argv[0]);
			printf("Las operaciones con matrices 3x3 implementadas son las siguientes:\n");
			printf("Pulse + para sumar las matrices\n");
			printf("Pulse - para restar las matrices\n");
			printf("Pulse x para hacer el producto de matrices\n");
			printf("Pulse e para hacer el producto escalar de matrices\n\n");
			exit(1);
			exit(1);

		}

		matriz_type m1;
		matriz_type m2;

		m1.v1.f1 = atof(argv[3]);
		m1.v1.f2 = atof(argv[4]);
		m1.v1.f3 = atof(argv[5]);
		m1.v2.f1 = atof(argv[6]);
		m1.v2.f2 = atof(argv[7]);
		m1.v2.f3 = atof(argv[8]);
		m1.v3.f1 = atof(argv[9]);
		m1.v3.f2 = atof(argv[10]);
		m1.v3.f3 = atof(argv[11]);

		m2.v1.f1 = atof(argv[12]);
		m2.v1.f2 = atof(argv[13]);
		m2.v1.f3 = atof(argv[14]);
		m2.v2.f1 = atof(argv[15]);
		m2.v2.f2 = atof(argv[16]);
		m2.v2.f3 = atof(argv[17]);
		m2.v3.f1 = atof(argv[18]);
		m2.v3.f2 = atof(argv[19]);
		m2.v3.f3 = atof(argv[20]);

		calculadoraprog_3 (host, m1, argv[2], m2);
	}
	
exit (0);
}
