/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "calculadora.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

calculadora_res1 *
calculadora_1(calculo1 arg1,  CLIENT *clnt)
{
	static calculadora_res1 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, CALCULADORA,
		(xdrproc_t) xdr_calculo1, (caddr_t) &arg1,
		(xdrproc_t) xdr_calculadora_res1, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

calculadora_res2 *
calculadora_2(calculo2 arg1,  CLIENT *clnt)
{
	static calculadora_res2 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, CALCULADORA,
		(xdrproc_t) xdr_calculo2, (caddr_t) &arg1,
		(xdrproc_t) xdr_calculadora_res2, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

calculadora_res3 *
calculadora_3(calculo3 arg1,  CLIENT *clnt)
{
	static calculadora_res3 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, CALCULADORA,
		(xdrproc_t) xdr_calculo3, (caddr_t) &arg1,
		(xdrproc_t) xdr_calculadora_res3, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
